services:
  - type: web
    name: learning-companion-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
